<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Soal;
use App\Models\Level;

class PatchSoalSeeder extends Seeder
{
    // ✅ MENGGUNAKAN UUID MILIK LEVEL "TIPE DATA" BUKAN "QUEUE"
    private const TIPE_DATA_LEVEL_ID = '01995dec-678e-70cf-854a-b25e2c2d0d28';

    public function run(): void
    {
        $levelTipeData = Level::where('id', self::TIPE_DATA_LEVEL_ID)->first();

        if (!$levelTipeData) {
            throw new \Exception('Level Tipe Data tidak ditemukan! Pastikan LevelSeeder sudah berjalan.');
        }

        $soalList = [
            ['id' => '01995df6-35ed-7363-9d42-578622c3e4f2', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Harga Motor', 'soal' => '<p>Pak Hari membeli sepeda motor dengan harga <strong>25.000.000 </strong>dan dikenakan pajak penjualan sebesar <strong>10%</strong>.<strong> </strong>Uang yang harus dibayar pak Hari sebesar…..</p>', 'kunci_tipe_data' => '[{"variabel":"pajak = 10%","tipe_data":"double","konversi":1},{"variabel":"harga_motor","tipe_data":"int","konversi":1},{"variabel":"uang_bayar","tipe_data":"int","konversi":1},{"variabel":"pajak_jual","tipe_data":"float","konversi":1}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"read pajak, harga_motor","clue":0,"konversi":0},{"langkah":"pajak_jual = pajak*harga_motor","clue":0,"konversi":1},{"langkah":"uang_bayar = harga_motor + pajak jual","clue":0,"konversi":1},{"langkah":"print (uang_bayar)","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 1, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => '01995e0a-74d3-73fa-895b-cfe6f4ec6ab6', 'id_level' => $levelTipeData->id, 'judul' => 'program Hitung Harga Jual', 'soal' => '<p>Sebuah rumah makan baru telah dibuka di Jl. Borobudur Malang. Berdasarkan peraturan pemerintah daerah maka rumah makan tersebut dikenakan pajak berdasarkan makanan yang dijual.&nbsp;Buatlah program Java untuk <strong>menghitung harga jual "Bakso Merapi" (Rp85.000)</strong> setelah ditambah <strong>pajak 10%</strong>. Program harus menampilkan output berupa harga akhir setelah terkena pajak!</p>', 'kunci_tipe_data' => '[{"variabel":"harga_dasar","tipe_data":"int","konversi":1},{"variabel":"persentase_pajak","tipe_data":"float","konversi":1},{"variabel":"harga_akhir","tipe_data":"int","konversi":1},{"variabel":"nilai_pajak","tipe_data":"float","konversi":1},{"variabel":"","tipe_data":"double","konversi":0}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"read harga_dasar = 85000;","clue":0,"konversi":1},{"langkah":"read persentase_pajak = 0.1;","clue":0,"konversi":1},{"langkah":"SET nilai_pajak = harga_dasar * persentase_pajak","clue":0,"konversi":1},{"langkah":"SET harga_akhir = harga_dasar + nilai_pajak","clue":0,"konversi":1},{"langkah":"PRINT \"Harga akhir setelah pajak: Rp\" +harga_akhir","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 13, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '01995e1e-b10a-70d3-8210-d2eee6fe2807', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Luas Kolam', 'soal' => '<p>Pak Budi mempunyai kolam renang berbentuk balok berukuran <strong>panjang 10 m</strong>, <strong>lebar 6 m</strong>, dan <strong>kedalaman 1,5 m</strong>. Sisi bagian dalam kolam renang dikeramik, luas bagian kolam renang yang dikeramik adalah</p>', 'kunci_tipe_data' => '[{"variabel":"panjang = 10m","tipe_data":"int","konversi":1},{"variabel":"lebar = 6m","tipe_data":"int","konversi":1},{"variabel":"tinggi = 1,5m","tipe_data":"float","konversi":1},{"variabel":"luas_bagian","tipe_data":"double","konversi":1},{"variabel":"","tipe_data":"int","konversi":0}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"read panjang, lebar, tinggi","clue":0,"konversi":0},{"langkah":"luas_bagian = 2 * ((p*l) + (p*t) + (l*t))","clue":0,"konversi":1},{"langkah":"print (luas_bagian)","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 14, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '01995e24-1a61-73eb-b623-a0220a69532e', 'id_level' => $levelTipeData->id, 'judul' => 'Perhitungan Volume', 'soal' => '<p>Pak Andi berencana untuk melakukan syukuran pada tanggal 31 Mei 2023. Untuk itu, Pak Andi mulai mempersiapkan pembelian box nasi, akan tetapi stok persediaan yang tersisa di toko hanyalah box nasi dengan perbandingan <strong>ukuran panjang : lebar : tinggi sebesar 20:20:7</strong>. Untuk mengetahui apakah box nasi ini cukup untuk menyimpan makanan yang akan dibagikan kepada para tamu, maka diperlukan <strong>perhitungan volume dari nasi box</strong>. Berdasarkan kondisi di atas, buatlah algoritma yang dapat menggambarkan proses <strong>perhitungan volume box nasi</strong>!</p>', 'kunci_tipe_data' => '[{"variabel":"Panjang","tipe_data":"int","konversi":1},{"variabel":"Lebar","tipe_data":"int","konversi":1},{"variabel":"Tinggi","tipe_data":"int","konversi":1},{"variabel":"volume","tipe_data":"long","konversi":1},{"variabel":"","tipe_data":"long","konversi":0}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"PRINT “Masukkan nilai panjang, lebar, tinggi”","clue":0,"konversi":1},{"langkah":"READ panjang, lebar, tinggi","clue":0,"konversi":0},{"langkah":"volume = panjang * lebar * tinggi","clue":0,"konversi":1},{"langkah":"PRINT “Volume setiap box nasi sebesar:” + volume","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 25, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '01995e27-3c16-7365-be30-b2fed20f53a2', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Luas Taman', 'soal' => '<p>Diketahui sebuah taman <strong>berbentuk lingkaran</strong>, yang mana setengah dari luas taman tersebut akan ditanami bunga. Jika jari-jari taman tersebut <strong>sebesar 42 meter</strong>, tentukan <strong>luas taman yang akan ditanami rumput</strong> dengan menggunakan algoritma pseudocode! <strong>(phi : 3,14)</strong></p>', 'kunci_tipe_data' => '[{"variabel":"r","tipe_data":"int","konversi":1},{"variabel":"phi","tipe_data":"float","konversi":1},{"variabel":"taman_bunga","tipe_data":"double","konversi":1}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"PRINT “Masukkan jari - jari taman, phi”","clue":0,"konversi":1},{"langkah":"READ r, phi","clue":0,"konversi":0},{"langkah":"taman_bunga = ½ (phi * 42 * 42)","clue":0,"konversi":1},{"langkah":"PRINT “Luas dari taman bunga sebesar:” + taman_bunga","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 2, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => '2d56c7b2-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Tabungan Andi di Bank', 'soal' => '<p>Andi menabung di bank sebesar <strong>2.500.000</strong>. Setiap bulan mendapat bunga <strong>5%</strong>. Hitung total tabungan!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "tabungan", "tipe_data": "int"}, {"konversi": 1, "variabel": "bunga", "tipe_data": "float"}, {"konversi": 1, "variabel": "hasil", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET tabungan = 2500000", "konversi": 1}, {"clue": 0, "langkah": "SET bunga = 0.05", "konversi": 1}, {"clue": 0, "langkah": "hasil = tabungan + (tabungan * bunga)", "konversi": 1}, {"clue": 0, "langkah": "PRINT hasil", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 1, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56d4e1-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Belanja Siti di Minimarket', 'soal' => '<p>Siti membeli barang seharga <strong>12.500</strong> dan <strong>7.500</strong> dengan diskon <strong>10%</strong>. Hitung total bayar!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "a", "tipe_data": "int"}, {"konversi": 1, "variabel": "b", "tipe_data": "int"}, {"konversi": 1, "variabel": "diskon", "tipe_data": "float"}, {"konversi": 1, "variabel": "total", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET a = 12500", "konversi": 1}, {"clue": 0, "langkah": "SET b = 7500", "konversi": 1}, {"clue": 0, "langkah": "SET diskon = 0.1", "konversi": 1}, {"clue": 0, "langkah": "total = (a + b) - ((a + b) * diskon)", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 2, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56da17-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Gaji dan Bonus Karyawan', 'soal' => '<p>Gaji <strong>3.000.000</strong> dan bonus <strong>750.000</strong>. Hitung total gaji!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "gaji", "tipe_data": "int"}, {"konversi": 1, "variabel": "bonus", "tipe_data": "int"}, {"konversi": 1, "variabel": "total", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET gaji = 3000000", "konversi": 1}, {"clue": 0, "langkah": "SET bonus = 750000", "konversi": 1}, {"clue": 0, "langkah": "total = gaji + bonus", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 3, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56dc1d-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Nilai Akhir Mahasiswa', 'soal' => '<p>Nilai: <strong>80, 75, 85</strong>. Hitung rata-rata!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "a", "tipe_data": "int"}, {"konversi": 1, "variabel": "b", "tipe_data": "int"}, {"konversi": 1, "variabel": "c", "tipe_data": "int"}, {"konversi": 1, "variabel": "rata", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET a = 80", "konversi": 1}, {"clue": 0, "langkah": "SET b = 75", "konversi": 1}, {"clue": 0, "langkah": "SET c = 85", "konversi": 1}, {"clue": 0, "langkah": "rata = (a + b + c) / 3", "konversi": 1}, {"clue": 0, "langkah": "PRINT rata", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 4, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56de1e-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Perjalanan Mobil', 'soal' => '<p>Kecepatan <strong>70 km/jam</strong> selama <strong>2.5 jam</strong>. Hitung jarak!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "kecepatan", "tipe_data": "int"}, {"konversi": 1, "variabel": "waktu", "tipe_data": "float"}, {"konversi": 1, "variabel": "jarak", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET kecepatan = 70", "konversi": 1}, {"clue": 0, "langkah": "SET waktu = 2.5", "konversi": 1}, {"clue": 0, "langkah": "jarak = kecepatan * waktu", "konversi": 1}, {"clue": 0, "langkah": "PRINT jarak", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 5, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56e00e-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Konversi Hari ke Menit', 'soal' => '<p><strong>1.5 hari</strong> = berapa menit?</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "hari", "tipe_data": "float"}, {"konversi": 1, "variabel": "menit", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET hari = 1.5", "konversi": 1}, {"clue": 0, "langkah": "menit = hari * 24 * 60", "konversi": 1}, {"clue": 0, "langkah": "PRINT menit", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 6, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56e417-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Harga Barang + Pajak', 'soal' => '<p>Harga <strong>200.000</strong>, pajak <strong>11%</strong>. Hitung total!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "harga", "tipe_data": "int"}, {"konversi": 1, "variabel": "pajak", "tipe_data": "float"}, {"konversi": 1, "variabel": "total", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET harga = 200000", "konversi": 1}, {"clue": 0, "langkah": "SET pajak = 0.11", "konversi": 1}, {"clue": 0, "langkah": "total = harga + (harga * pajak)", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 7, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56e823-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Konversi Jam ke Detik', 'soal' => '<p><strong>1.5 jam</strong> = berapa detik?</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "jam", "tipe_data": "float"}, {"konversi": 1, "variabel": "detik", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET jam = 1.5", "konversi": 1}, {"clue": 0, "langkah": "detik = jam * 3600", "konversi": 1}, {"clue": 0, "langkah": "PRINT detik", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 8, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56ec21-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Tiket Bioskop', 'soal' => '<p>Harga tiket <strong>45.000</strong>, beli <strong>3</strong>, pajak <strong>10%</strong>. Hitung total!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "harga", "tipe_data": "int"}, {"konversi": 1, "variabel": "jumlah", "tipe_data": "int"}, {"konversi": 1, "variabel": "pajak", "tipe_data": "float"}, {"konversi": 1, "variabel": "total", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET harga = 45000", "konversi": 1}, {"clue": 0, "langkah": "SET jumlah = 3", "konversi": 1}, {"clue": 0, "langkah": "SET pajak = 0.1", "konversi": 1}, {"clue": 0, "langkah": "total = (harga * jumlah) + ((harga * jumlah) * pajak)", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 9, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '2d56f072-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Volume Air Tangki', 'soal' => '<p>Debit <strong>2.5 liter/detik</strong> selama <strong>40 detik</strong>. Hitung volume!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "debit", "tipe_data": "float"}, {"konversi": 1, "variabel": "waktu", "tipe_data": "int"}, {"konversi": 1, "variabel": "volume", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET debit = 2.5", "konversi": 1}, {"clue": 0, "langkah": "SET waktu = 40", "konversi": 1}, {"clue": 0, "langkah": "volume = debit * waktu", "konversi": 1}, {"clue": 0, "langkah": "PRINT volume", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 10, 'status' => 1, 'difficulty' => 'medium'],
            ['id' => '97c001ae-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Total Belanja + Diskon Bertingkat', 'soal' => '<p>Rina berbelanja sebesar <strong>200.000</strong>. Jika diskon 10% dan pajak 5%, hitung total bayar!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "harga", "tipe_data": "int"}, {"konversi": 1, "variabel": "diskon", "tipe_data": "float"}, {"konversi": 1, "variabel": "pajak", "tipe_data": "float"}, {"konversi": 1, "variabel": "total", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET harga = 200000", "konversi": 1}, {"clue": 0, "langkah": "SET diskon = 0.1", "konversi": 1}, {"clue": 0, "langkah": "SET pajak = 0.05", "konversi": 1}, {"clue": 0, "langkah": "harga = harga - (harga * diskon)", "konversi": 1}, {"clue": 0, "langkah": "total = harga + (harga * pajak)", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 1, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c00fc2-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Konversi Suhu Celcius ke Fahrenheit', 'soal' => '<p>Suhu adalah <strong>30°C</strong>. Hitung dalam Fahrenheit!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "c", "tipe_data": "int"}, {"konversi": 1, "variabel": "f", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET c = 30", "konversi": 1}, {"clue": 0, "langkah": "f = (c * 9/5) + 32", "konversi": 1}, {"clue": 0, "langkah": "PRINT f", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 2, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c012c2-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Total Gaji dengan Lembur', 'soal' => '<p>Gaji pokok <strong>3.000.000</strong>, lembur 10 jam dengan tarif <strong>25.000/jam</strong>. Hitung total!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "gaji", "tipe_data": "int"}, {"konversi": 1, "variabel": "lembur", "tipe_data": "int"}, {"konversi": 1, "variabel": "tarif", "tipe_data": "int"}, {"konversi": 1, "variabel": "total", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET gaji = 3000000", "konversi": 1}, {"clue": 0, "langkah": "SET lembur = 10", "konversi": 1}, {"clue": 0, "langkah": "SET tarif = 25000", "konversi": 1}, {"clue": 0, "langkah": "total = gaji + (lembur * tarif)", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 3, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c01571-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Kecepatan Rata-rata', 'soal' => '<p>Mobil menempuh 150 km dalam 3 jam. Hitung kecepatan!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "jarak", "tipe_data": "int"}, {"konversi": 1, "variabel": "waktu", "tipe_data": "int"}, {"konversi": 1, "variabel": "kecepatan", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET jarak = 150", "konversi": 1}, {"clue": 0, "langkah": "SET waktu = 3", "konversi": 1}, {"clue": 0, "langkah": "kecepatan = (float) jarak / waktu", "konversi": 1}, {"clue": 0, "langkah": "PRINT kecepatan", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 4, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c01d57-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Hitung BMI', 'soal' => '<p>Berat badan 60 kg dan tinggi 1.7 m. Hitung BMI!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "berat", "tipe_data": "int"}, {"konversi": 1, "variabel": "tinggi", "tipe_data": "float"}, {"konversi": 1, "variabel": "bmi", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET berat = 60", "konversi": 1}, {"clue": 0, "langkah": "SET tinggi = 1.7", "konversi": 1}, {"clue": 0, "langkah": "bmi = berat / (tinggi * tinggi)", "konversi": 1}, {"clue": 0, "langkah": "PRINT bmi", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 5, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c02041-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Total Harga + Ongkir', 'soal' => '<p>Harga barang 120.000 dan ongkir 15.000. Hitung total bayar!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "harga", "tipe_data": "int"}, {"konversi": 1, "variabel": "ongkir", "tipe_data": "int"}, {"konversi": 1, "variabel": "total", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET harga = 120000", "konversi": 1}, {"clue": 0, "langkah": "SET ongkir = 15000", "konversi": 1}, {"clue": 0, "langkah": "total = harga + ongkir", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 6, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c02377-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Konversi Km ke Meter dan Cm', 'soal' => '<p>Jarak 2 km. Konversi ke meter dan cm!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "km", "tipe_data": "int"}, {"konversi": 1, "variabel": "meter", "tipe_data": "int"}, {"konversi": 1, "variabel": "cm", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET km = 2", "konversi": 1}, {"clue": 0, "langkah": "meter = km * 1000", "konversi": 1}, {"clue": 0, "langkah": "cm = meter * 100", "konversi": 1}, {"clue": 0, "langkah": "PRINT cm", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 7, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c02606-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Total Nilai Akhir Mahasiswa', 'soal' => '<p>Tugas 80, UTS 75, UAS 90. Bobot masing-masing 30%, 30%, 40%.</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "tugas", "tipe_data": "int"}, {"konversi": 1, "variabel": "uts", "tipe_data": "int"}, {"konversi": 1, "variabel": "uas", "tipe_data": "int"}, {"konversi": 1, "variabel": "akhir", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET tugas = 80", "konversi": 1}, {"clue": 0, "langkah": "SET uts = 75", "konversi": 1}, {"clue": 0, "langkah": "SET uas = 90", "konversi": 1}, {"clue": 0, "langkah": "akhir = (tugas*0.3) + (uts*0.3) + (uas*0.4)", "konversi": 1}, {"clue": 0, "langkah": "PRINT akhir", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 8, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c028a3-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Waktu Total dalam Detik', 'soal' => '<p>1 jam 2 menit 30 detik. Hitung total detik!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "jam", "tipe_data": "int"}, {"konversi": 1, "variabel": "menit", "tipe_data": "int"}, {"konversi": 1, "variabel": "detik", "tipe_data": "int"}, {"konversi": 1, "variabel": "total", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET jam = 1", "konversi": 1}, {"clue": 0, "langkah": "SET menit = 2", "konversi": 1}, {"clue": 0, "langkah": "SET detik = 30", "konversi": 1}, {"clue": 0, "langkah": "total = (jam*3600) + (menit*60) + detik", "konversi": 1}, {"clue": 0, "langkah": "PRINT total", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 9, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => '97c02b33-37d0-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Hitung Luas dan Keliling Lingkaran', 'soal' => '<p>Jari-jari 14 cm. Hitung luas dan keliling (phi = 3.14)</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "r", "tipe_data": "int"}, {"konversi": 1, "variabel": "phi", "tipe_data": "float"}, {"konversi": 1, "variabel": "luas", "tipe_data": "float"}, {"konversi": 1, "variabel": "keliling", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET r = 14", "konversi": 1}, {"clue": 0, "langkah": "SET phi = 3.14", "konversi": 1}, {"clue": 0, "langkah": "luas = phi * r * r", "konversi": 1}, {"clue": 0, "langkah": "keliling = 2 * phi * r", "konversi": 1}, {"clue": 0, "langkah": "PRINT luas", "konversi": 1}, {"clue": 0, "langkah": "PRINT keliling", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 10, 'status' => 1, 'difficulty' => 'hard'],
            ['id' => 'c2b71702-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Luas Persegi', 'soal' => '<p>Diketahui sebuah persegi memiliki sisi <strong>8 cm</strong>. Hitung luas persegi tersebut!</p>', 'kunci_tipe_data' => '[{"variabel":"sisi","tipe_data":"int","konversi":1},{"variabel":"luas","tipe_data":"int","konversi":1}]', 'kunci_algoritma' => '[{"langkah":"START","clue":0,"konversi":0},{"langkah":"sisi = 8","clue":0,"konversi":1},{"langkah":"luas = sisi * sisi","clue":0,"konversi":1},{"langkah":"PRINT luas","clue":0,"konversi":1},{"langkah":"END","clue":0,"konversi":0}]', 'order' => 1, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b72823-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Kecepatan', 'soal' => '<p>Sebuah kendaraan menempuh jarak <strong>100 km</strong> dalam waktu <strong>2 jam</strong>. Hitung kecepatannya!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "jarak", "tipe_data": "int"}, {"konversi": 1, "variabel": "waktu", "tipe_data": "int"}, {"konversi": 1, "variabel": "kecepatan", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET jarak = 100", "konversi": 1}, {"clue": 0, "langkah": "SET waktu = 2", "konversi": 1}, {"clue": 0, "langkah": "kecepatan = jarak / waktu", "konversi": 1}, {"clue": 0, "langkah": "PRINT kecepatan", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 10, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b730ed-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Keliling Persegi Panjang', 'soal' => '<p>Sebuah persegi panjang memiliki panjang <strong>10 cm</strong> dan lebar <strong>5 cm</strong>. Hitung kelilingnya!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "panjang", "tipe_data": "int"}, {"konversi": 1, "variabel": "lebar", "tipe_data": "int"}, {"konversi": 1, "variabel": "keliling", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET panjang = 10", "konversi": 1}, {"clue": 0, "langkah": "SET lebar = 5", "konversi": 1}, {"clue": 0, "langkah": "keliling = 2 * (panjang + lebar)", "konversi": 1}, {"clue": 0, "langkah": "PRINT keliling", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 2, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b739b3-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Volume Kubus', 'soal' => '<p>Sebuah kubus memiliki panjang sisi <strong>4 cm</strong>. Hitung volume kubus!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "sisi", "tipe_data": "int"}, {"konversi": 1, "variabel": "volume", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET sisi = 4", "konversi": 1}, {"clue": 0, "langkah": "volume = sisi * sisi * sisi", "konversi": 1}, {"clue": 0, "langkah": "PRINT volume", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 3, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b74375-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Luas Segitiga', 'soal' => '<p>Sebuah segitiga memiliki alas <strong>6 cm</strong> dan tinggi <strong>4 cm</strong>. Hitung luasnya!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "alas", "tipe_data": "int"}, {"konversi": 1, "variabel": "tinggi", "tipe_data": "int"}, {"konversi": 1, "variabel": "luas", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET alas = 6", "konversi": 1}, {"clue": 0, "langkah": "SET tinggi = 4", "konversi": 1}, {"clue": 0, "langkah": "luas = 0.5 * alas * tinggi", "konversi": 1}, {"clue": 0, "langkah": "PRINT luas", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 4, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b74bda-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Rata-rata', 'soal' => '<p>Diketahui tiga bilangan: <strong>10, 15, 20</strong>. Hitung rata-ratanya!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "a", "tipe_data": "int"}, {"konversi": 1, "variabel": "b", "tipe_data": "int"}, {"konversi": 1, "variabel": "c", "tipe_data": "int"}, {"konversi": 1, "variabel": "rata", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET a = 10", "konversi": 1}, {"clue": 0, "langkah": "SET b = 15", "konversi": 1}, {"clue": 0, "langkah": "SET c = 20", "konversi": 1}, {"clue": 0, "langkah": "rata = (a + b + c) / 3", "konversi": 1}, {"clue": 0, "langkah": "PRINT rata", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 5, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b75505-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Diskon', 'soal' => '<p>Harga sebuah barang adalah <strong>50000</strong> dengan diskon <strong>10%</strong>. Hitung harga setelah diskon!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "harga", "tipe_data": "int"}, {"konversi": 1, "variabel": "diskon", "tipe_data": "float"}, {"konversi": 1, "variabel": "potongan", "tipe_data": "float"}, {"konversi": 1, "variabel": "harga_akhir", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET harga = 50000", "konversi": 1}, {"clue": 0, "langkah": "SET diskon = 0.1", "konversi": 1}, {"clue": 0, "langkah": "potongan = harga * diskon", "konversi": 1}, {"clue": 0, "langkah": "harga_akhir = harga - potongan", "konversi": 1}, {"clue": 0, "langkah": "PRINT harga_akhir", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 6, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b75d37-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Konversi Jam ke Menit', 'soal' => '<p>Sebuah waktu adalah <strong>2 jam</strong>. Konversikan ke menit!</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "jam", "tipe_data": "int"}, {"konversi": 1, "variabel": "menit", "tipe_data": "int"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET jam = 2", "konversi": 1}, {"clue": 0, "langkah": "menit = jam * 60", "konversi": 1}, {"clue": 0, "langkah": "PRINT menit", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 7, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b76532-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Luas Lingkaran', 'soal' => '<p>Sebuah lingkaran memiliki jari-jari <strong>7 cm</strong>. Hitung luasnya! (phi = 3.14)</p>', 'kunci_tipe_data' => '[{"konversi": 1, "variabel": "r", "tipe_data": "int"}, {"konversi": 1, "variabel": "phi", "tipe_data": "float"}, {"konversi": 1, "variabel": "luas", "tipe_data": "float"}]', 'kunci_algoritma' => '[{"clue": 0, "langkah": "START", "konversi": 0}, {"clue": 0, "langkah": "SET r = 7", "konversi": 1}, {"clue": 0, "langkah": "SET phi = 3.14", "konversi": 1}, {"clue": 0, "langkah": "luas = phi * r * r", "konversi": 1}, {"clue": 0, "langkah": "PRINT luas", "konversi": 1}, {"clue": 0, "langkah": "END", "konversi": 0}]', 'order' => 8, 'status' => 1, 'difficulty' => 'easy'],
            ['id' => 'c2b76d01-37d4-11f1-b439-0a0027000014', 'id_level' => $levelTipeData->id, 'judul' => 'Program Hitung Gaji', 'soal' => '<p>Gaji harian seorang pekerja adalah <strong>100000</strong>. Jika ia bekerja selama <strong>5 hari</strong>, hitung total gaji!</p>', 'kunci_tipe_data' => '[{"variabel": "gaji_harian", "tipe_data": "int", "konversi": 1}, {"variabel": "hari", "tipe_data": "int", "konversi": 1}, {"variabel": "total", "tipe_data": "int", "konversi": 1}]', 'kunci_algoritma' => '[{"langkah": "START", "clue": 0, "konversi": 0}, {"langkah": "SET gaji_harian = 100000", "clue": 0, "konversi": 1}, {"langkah": "SET hari = 5", "clue": 0, "konversi": 1}, {"langkah": "total = gaji_harian * hari", "clue": 0, "konversi": 1}, {"langkah": "PRINT total", "clue": 0, "konversi": 1}, {"langkah": "END", "clue": 0, "konversi": 0}]', 'order' => 9, 'status' => 1, 'difficulty' => 'easy'],
        ];

        foreach ($soalList as $data) {
            Soal::updateOrCreate(
                ['id' => $data['id']], 
                [
                    'id_level' => $data['id_level'],
                    'judul' => $data['judul'],
                    'soal' => $data['soal'],
                    'kunci_tipe_data' => $data['kunci_tipe_data'],
                    'kunci_algoritma' => $data['kunci_algoritma'],
                    'order' => $data['order'],
                    'status' => $data['status'],
                    'difficulty' => $data['difficulty'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}