<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SoalSeeder extends Seeder
{
    public function run(): void
    {
        $queue2LevelId = '019e5940-c171-73e1-a8e0-0e32d3e79b5f';
        $linkedListLevelId = '019de356-abfa-717d-958c-e9311c2712f3';
        $queueLamaLevelId = '019863c4-59f9-7319-9104-08267fc3c551';
        $now     = now();

        $soalList = [
            // ============================================================
            // QUEUE: EASY (5 Soal)
            // ============================================================
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Operasi Enqueue dan Print pada Antrian',
                'soal'            => '<p>Sebuah sistem antrian menerima dua data berturut-turut yaitu 15 dan 30 menggunakan operasi <code>enqueue()</code>. Setelah kedua data dimasukkan, sistem memanggil fungsi <code>print()</code> untuk menampilkan seluruh isi antrian dari depan ke belakang.</p><p>Tentukan output dari sistem tersebut.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(15)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(30)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() menampilkan 15 lalu 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 1, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Operasi Dequeue dan Print pada Antrian',
                'soal'            => '<p>Terdapat antrian dengan data awal 10, 20, dan 30. Sistem kemudian menjalankan operasi <code>dequeue()</code> satu kali untuk mengeluarkan elemen terdepan. Setelah itu, fungsi <code>print()</code> dipanggil.</p><p>Tentukan sisa elemen yang dicetak oleh sistem.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Antrian berisi 10, 20, 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() dijalankan, angka 10 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() menampilkan sisa elemen: 20 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 2, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Antrian Barang Gudang (Enqueue & Print)',
                'soal'            => '<p>Sebuah gudang mencatat barang masuk ke dalam antrian. Tiga barang dengan ID 100, 200, dan 300 dimasukkan berturut-turut menggunakan operasi <code>enqueue()</code>. Setelah itu, petugas memanggil fungsi <code>print()</code> untuk melihat isi antrian.</p><p>Tentukan output yang akan tercetak.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(100), enqueue(200), enqueue(300)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() menampilkan 100 200 300', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 3, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Pengurangan Antrian Loket (Dequeue & Print)',
                'soal'            => '<p>Antrian loket awalnya berisi antrian 1, 2, 3, dan 4. Petugas memanggil dua orang pertama sehingga operasi <code>dequeue()</code> dijalankan sebanyak dua kali. Kemudian petugas mengecek sisa antrian dengan operasi <code>print()</code>.</p><p>Tentukan sisa antrian yang dicetak.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Antrian berisi 1, 2, 3, 4', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() 2 kali (1 dan 2 keluar)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() menampilkan sisa elemen: 3 4', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 4, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Pencatatan Cepat Antrian (Enqueue & Print)',
                'soal'            => '<p>Sistem menerima input antrian nilai 88 menggunakan <code>enqueue()</code>, lalu langsung mencetaknya menggunakan <code>print()</code>. Kemudian, nilai 99 masuk dengan <code>enqueue()</code>, dan sistem kembali memanggil <code>print()</code>.</p><p>Tentukan output baris pertama dan kedua dari sistem.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(88) lalu print()', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(99) lalu print()', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 5, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ============================================================
            // QUEUE: MEDIUM (5 Soal)
            // ============================================================
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Cek Kapasitas dan Peek Antrian Layanan',
                'soal'            => '<p>Sebuah program antrian menggunakan Scanner untuk menerima kapasitas maksimal. Pengguna memasukkan kapasitas 2. Kemudian, sistem mengecek apakah antrian penuh menggunakan <code>IsFull()</code>. Selanjutnya, data 101 dimasukkan dengan <code>enqueue()</code> dan sistem mengecek elemen terdepan menggunakan <code>peek()</code>.</p><p>Tentukan output pengecekan kapasitas dan nilai elemen terdepan.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: max = 2', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'IsFull() -> false', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(101)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'peek() -> Elemen terdepan: 101', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 6, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Mengosongkan Sisa Antrian',
                'soal'            => '<p>Tanpa menggunakan input Scanner, sebuah antrian diisi dengan data 55 dan 66. Program lalu menjalankan <code>dequeue()</code> satu kali, disusul dengan pemanggilan <code>clear()</code>. Terakhir, program memanggil <code>IsEmpty()</code>.</p><p>Tentukan status <code>IsEmpty()</code> di akhir program.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'status', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(55), enqueue(66)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 55 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'clear() -> sisa elemen dihapus', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'IsEmpty() -> true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 7, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Simulasi Operasi Layanan Queue',
                'soal'            => '<p>Dengan menggunakan Scanner, program menerima input 3 buah data secara berurutan: 5, 15, 25 untuk di-<code>enqueue()</code>. Program mencetak isi antrian dengan <code>print()</code>, lalu melakukan <code>dequeue()</code> satu kali, dan memanggil <code>print()</code> lagi.</p><p>Bagaimana bentuk output print pertama dan kedua?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'dt', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input 5, 15, 25 lalu enqueue()', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() -> 5 15 25', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 5 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() -> 15 25', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 8, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Batas Kapasitas Antrian',
                'soal'            => '<p>Menggunakan Scanner, admin mengatur kapasitas antrian maksimal (<code>max</code>) sebesar 3. Admin kemudian memasukkan angka 10, 20, dan 30 secara berurutan menggunakan <code>enqueue()</code>. Setelah itu, sistem mengecek apakah antrian sudah penuh dengan memanggil fungsi <code>IsFull()</code>, dilanjutkan dengan <code>peek()</code> untuk melihat antrian terdepan.</p><p>Tentukan status boolean <code>IsFull()</code> dan hasil dari <code>peek()</code>.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner max = 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(10), enqueue(20), enqueue(30)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'IsFull() -> true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'peek() -> Elemen terdepan: 10', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 9, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Reset Ulang Antrian Pelanggan',
                'soal'            => '<p>Sebuah toko (tanpa Scanner) memasukkan nomor antrian 5, 6, dan 7 menggunakan <code>enqueue()</code>. Kasir mencetak antrian dengan <code>print()</code>. Karena sistem error, kasir memanggil fungsi <code>clear()</code> untuk mengosongkan seluruh antrian, dan kemudian mengeceknya menggunakan <code>IsEmpty()</code>.</p><p>Tentukan output cetakan pertama dan status <code>IsEmpty()</code> setelah di-clear.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'status', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(5), enqueue(6), enqueue(7)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() -> 5 6 7', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'clear() -> antrian dikosongkan', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'IsEmpty() -> true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 10, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],

            // ============================================================
            // QUEUE: HARD (5 Soal)
            // ============================================================
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Batas Kapasitas Antrean Wahana Bermain',
                'soal'            => '<p>Sebuah taman bermain menggunakan Scanner untuk mengatur kapasitas (<code>max</code>) antrean wahana. Petugas memasukkan batas kapasitas 3. Ada 5 anak dengan ID: 11, 22, 33, 44, dan 55 yang masuk antrean satu per satu. Jika antrean penuh (<code>IsFull()</code>), sistem langsung mencetak "Penuh" dan proses dihentikan (break).</p><p>Berapa banyak anak yang berhasil masuk ke antrean?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner max = 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop elemen: 11, 22, 33, 44, 55', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(11), enqueue(22), enqueue(33)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Saat elemen 44 masuk, IsFull() true -> cetak Penuh, lalu break', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print total ukuran antrean -> 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 11, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Simulasi Reset Antrean Otomatis di Klinik',
                'soal'            => '<p>Di sebuah klinik (tanpa Scanner), 3 pasien mendaftar dengan ID: 101, 102, 103 menggunakan <code>enqueue()</code>. Dokter kemudian memanggil ketiga pasien secara berurutan menggunakan <code>dequeue()</code>. Setiap kali <code>dequeue()</code> dijalankan, sistem mengecek: jika nilai <code>front &gt; rear</code>, maka sistem langsung me-reset <code>front</code> dan <code>rear</code> menjadi -1.</p><p>Berapakah nilai <code>front</code> dan <code>rear</code> di akhir program?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'front', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(101), enqueue(102), enqueue(103)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 101, dequeue() -> 102', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 103, front naik melewati rear', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Kondisi front > rear true -> reset front = -1, rear = -1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print Front dan Rear', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 12, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Pengarsipan Digital Antrean ke Stack',
                'soal'            => '<p>Sistem perpustakaan menerima 3 ID buku menggunakan Scanner: 1, 2, dan 3 yang dimasukkan ke antrean menggunakan <code>enqueue()</code>. Di sore hari, sistem memindahkan seluruh buku tersebut dari Queue ke dalam arsip (Stack). Selama antrean tidak kosong (<code>IsEmpty()</code>), sistem akan melakukan <code>dequeue()</code> dan datanya langsung di-<code>push()</code> ke Stack.</p><p>Tentukan ID buku yang berada di posisi paling atas (top) pada arsip Stack.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'q', 'tipe_data' => 'Queue', 'konversi' => 0],
                    ['variabel' => 'st', 'tipe_data' => 'Stack', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: enqueue(1), enqueue(2), enqueue(3)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop: dequeue() -> push() berulang hingga IsEmpty() true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue(1) -> push(1)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue(2) -> push(2)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue(3) -> push(3)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print elemen top dari Stack -> 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 13, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Pembalikan Urutan Mobil Keluar Gang',
                'soal'            => '<p>Tiga mobil terjebak di gang buntu dengan antrean [1, 2, 3]. Untuk keluar, mereka harus diputar balik menjadi [3, 2, 1] tanpa Scanner. Tekniknya: pindahkan seluruh mobil dari Queue ke dalam tumpukan sementara (Stack) menggunakan <code>dequeue()</code> dan <code>push()</code>. Setelah antrean dikosongkan, mobil dikembalikan dari Stack ke Queue menggunakan <code>pop()</code> dan <code>enqueue()</code>.</p><p>Tentukan hasil cetakan antrean setelah dibalik.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'q', 'tipe_data' => 'Queue', 'konversi' => 0],
                    ['variabel' => 'st', 'tipe_data' => 'Stack', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(1), enqueue(2), enqueue(3)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Pindahkan ke Stack: push(dequeue()) hingga IsEmpty() true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Reset index Queue', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Pindahkan kembali: enqueue(pop()) hingga Stack kosong', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print() -> 3 2 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 14, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queue2LevelId,
                'judul'           => 'Validasi Antrean Palindrom',
                'soal'            => '<p>Sistem mengecek apakah 3 tiket yang dimasukkan pengunjung dengan Scanner merupakan urutan palindrom (misal: 1 2 1). Setiap input langsung dimasukkan ke Queue (<code>enqueue()</code>) dan ke Stack (<code>push()</code>) sekaligus. Kemudian, elemen diuji dengan membandingkan hasil <code>dequeue()</code> dengan <code>pop()</code>.</p><p>Jika input yang diberikan adalah 1, 2, dan 1, tentukan apakah susunan tiket tersebut membentuk palindrom.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'isPalin', 'tipe_data' => 'boolean', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: 1, 2, 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Simpan ke Queue dan Stack secara bersamaan', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop pengecekan: Bandingkan dequeue() dengan pop()', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '1 == 1, 2 == 2, 1 == 1. Semua sama, isPalin = true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print nilai isPalin', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 15, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
        ];

        // Linked List
        $linkedListSoalList = [
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menyambung Tiga Gerbong Kereta',
                'soal'            => '<p>Sebuah kereta barang dirangkai menggunakan konsep Single Linked List. Gerbong pertama (head) memiliki beban 10 ton. Kemudian disambungkan gerbong kedua dengan 20 ton, dan gerbong ketiga 30 ton.</p><p>Buat simpul untuk ketiga gerbong tersebut lalu cetak beban pada gerbong pertama dan gerbong terakhir secara berurutan.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat node head dengan nilai 10', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan head.next dengan node baru bernilai 20', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan head.next.next dengan node baru bernilai 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT nilai dari head (Depan)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT nilai dari head.next.next (Belakang)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 1, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menghitung Total Gerbong Kereta',
                'soal'            => '<p>Rangkaian gerbong kereta (SLL) berisi daftar kode barang: "A", "B", dan "C". Petugas ingin menghitung berapa total gerbong yang ada dalam rangkaian tersebut menggunakan perulangan.</p><p>Tentukan total jumlah gerbong dengan menelusuri Linked List dari depan hingga akhir.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'count', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat node A, B, C dan sambungkan menjadi A -> B -> C', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set count = 0, Node sementara = head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA sementara tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  tambah count dengan 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  pindahkan sementara ke node selanjutnya (sementara = sementara.next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT jumlah gerbong', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 2, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menambah Gerbong di Paling Depan',
                'soal'            => '<p>Sebuah rangkaian gerbong SLL saat ini memiliki isi "B" lalu "C". Kepala stasiun memerintahkan untuk menyisipkan gerbong baru berisi "A" tepat di posisi paling depan (menjadi head baru).</p><p>Sisipkan gerbong "A" di depan "B", kemudian cetak seluruh isi rangkaian dari depan ke belakang.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'baru', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL awal: head = B, head.next = C', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat node baru = A', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan node baru ke head awal (baru.next = head)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Ubah head menjadi node baru (head = baru)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri dan PRINT semua isi SLL', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 3, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Navigasi Playlist Lagu Maju dan Mundur',
                'soal'            => '<p>Sebuah aplikasi musik menggunakan Double Linked List (DLL) untuk menyimpan playlist. Terdapat dua lagu: "Lagu1" dan "Lagu2". Lagu dapat diputar ke lagu selanjutnya (next) atau kembali ke lagu sebelumnya (prev).</p><p>Buatlah DLL untuk kedua lagu tersebut, lalu cetak urutan maju dan urutan mundur dengan memanfaatkan pointer next dan prev.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'lagu1', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'lagu2', 'tipe_data' => 'DNode', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat DNode l1 (Lagu1) dan l2 (Lagu2)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'l1.next = l2', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'l2.prev = l1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT Maju: l1 lalu l1.next', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT Mundur: l2 lalu l2.prev', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 4, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menampilkan Seluruh Daftar Pesanan Makanan',
                'soal'            => '<p>Sebuah restoran mencatat pesanan Sate, Soto, dan Bakso ke dalam Single Linked List secara berurutan. Pelayan ingin melihat semua daftar pesanan yang masuk dari pesanan pertama hingga terakhir.</p><p>Lakukan traversal (penelusuran) pada LinkedList dan cetak setiap pesanan ke layar.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'tmp', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL: Sate -> Soto -> Bakso', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set node sementara = head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA sementara tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  PRINT data pada node sementara', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  sementara = sementara.next', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 5, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Mencari Buku di Rak Perpustakaan',
                'soal'            => '<p>Rak buku perpustakaan menyimpan ID buku dalam Single Linked List dengan urutan: 101, 102, dan 103. Pustakawan ingin mengecek apakah ID buku <strong>102</strong> tersedia di rak tersebut.</p><p>Telusuri SLL dari awal. Jika ditemukan, ubah status menjadi TRUE, lalu cetak hasil penemuannya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'ada', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL dengan urutan 101 -> 102 -> 103', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Tentukan target yang dicari = 102', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set boolean ada = false, sementara = head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN penelusuran sampai node habis:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  JIKA nilai node == target MAKA ada = true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  pindah ke node berikutnya', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT status ditemukan (ada)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 6, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menghapus Pasien Pertama dari Antrian',
                'soal'            => '<p>Antrian klinik (SLL) berisi nomor pasien 1, 2, dan 3. Pasien nomor 1 telah selesai diperiksa, sehingga petugas harus menghapus pasien pertama dari depan (menghapus head).</p><p>Hapus elemen paling depan SLL tersebut, lalu cetak sisa antrian.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat antrian 1 -> 2 -> 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'JIKA head tidak kosong MAKA:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  Ubah head ke elemen berikutnya (head = head.next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Lakukan penelusuran untuk PRINT semua sisa antrian', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 7, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Melepas Gerbong Terakhir Kereta',
                'soal'            => '<p>Rangkaian Double Linked List menyimpan nilai gerbong 10 <-> 20 <-> 30. Karena beban terlalu berat, petugas mekanik memotong dan melepas gerbong paling belakang (tail = 30).</p><p>Temukan gerbong terakhir, putus sambungannya, lalu cetak isi dari depan ke belakang.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'temp', 'tipe_data' => 'DNode', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat DLL: 10 <-> 20 <-> 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri sampai menemukan node terakhir (temp.next == null)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Putus sambungan dari node sebelum terakhir (temp.prev.next = null)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri dari head untuk PRINT sisa gerbong', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 8, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menyisipkan Peserta di Tengah Barisan',
                'soal'            => '<p>Barisan Single Linked List awalnya berisi "Budi" yang menyambung ke "Doni". Tiba-tiba "Caca" datang dan petugas menyisipkan Caca tepat di antara Budi dan Doni.</p><p>Lakukan proses <em>Insert After</em> pada node Budi, lalu cetak urutan barisan yang baru.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'caca', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL: head(Budi) -> node(Doni)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat node baru Caca', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan next dari Caca ke Doni (caca.next = head.next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan next dari Budi ke Caca (head.next = caca)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri dan PRINT seluruh barisan baru', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 9, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menghitung Total Belanjaan di Kasir',
                'soal'            => '<p>Kasir menyimpan riwayat harga belanja pelanggan di Single Linked List dengan data: 5000, 10000, dan 15000. Kasir ingin menghitung jumlah keseluruhan belanjaan secara otomatis.</p><p>Telusuri elemen dari depan, jumlahkan nilainya ke dalam satu variabel, lalu cetak totalnya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'total', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL berisi: 5000 -> 10000 -> 15000', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set total = 0, node sementara = head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA sementara tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  tambahkan nilai pada node sementara ke variabel total', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  pindah ke node berikutnya', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT total akhir belanjaan', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 10, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Mencari Skor Peserta Tertinggi',
                'soal'            => '<p>Panitia lomba menyimpan daftar skor (80, 95, 75) ke dalam Single Linked List. Untuk mencari pemenang, panitia perlu membandingkan semua skor secara iteratif.</p><p>Telusuri seluruh SLL, tentukan nilai skor paling tinggi, dan cetak skor maksimum tersebut.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'maksimum', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL berisi skor: 80 -> 95 -> 75', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set maksimum = nilai head (80), lalu pindah cek ke node berikutnya', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA node belum habis:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  JIKA nilai node sekarang > maksimum MAKA maksimum = nilai node sekarang', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  pindah ke node berikutnya', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT nilai maksimum', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 11, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Membalik Urutan Antrian Pemain',
                'soal'            => '<p>Tiga peserta masuk SLL dengan urutan 1 -> 2 -> 3. Petugas ingin membalik urutan (Reverse) sehingga yang terakhir menjadi yang pertama (3 -> 2 -> 1) hanya dengan mengubah manipulasi pointer "next" dari setiap Node.</p><p>Balik urutan SLL tersebut, ubah head menjadi node bernilai 3, lalu cetak urutan barunya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'prev', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'curr', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL awal: 1 -> 2 -> 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set Node prev = null, curr = head, next = null', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA curr tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  simpan alamat next (next = curr.next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  balik arah sambungan (curr.next = prev)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  geser prev dan curr maju (prev = curr, curr = next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Ubah head menjadi prev', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri dan PRINT hasil SLL yang dibalik', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 12, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Menyisipkan Data di Tengah Double Linked List',
                'soal'            => '<p>Double Linked List menyimpan dua node: 10 (head) yang langsung menyambung ke 30 (tail). Buatlah program untuk menyisipkan node bernilai 20 agar berada pas di tengah-tengah antara 10 dan 30.</p><p>Sambungkan dengan benar pointer next dan prev, lalu cetak urutannya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'baru', 'tipe_data' => 'DNode', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat DNode l1(10) dan l3(30). Sambungkan l1 <-> l3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat node baru l2 dengan nilai 20', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan l2.next ke l1.next (menuju 30)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Sambungkan l2.prev ke l1 (menuju 10)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Ubah prev dari 30 menjadi l2 (l1.next.prev = l2)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Ubah next dari 10 menjadi l2 (l1.next = l2)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT seluruh DLL dari head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 13, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Mencabut Berkas Rusak di Tengah Urutan',
                'soal'            => '<p>SLL menyimpan ID berkas: 5 -> 10 -> 15. Berkas ber-ID <strong>10</strong> dianggap rusak dan harus dihapus. Kita harus menelusuri dari awal untuk mencari node 10, mencatat node sebelumnya, dan menyambungkan pointer melewati node yang rusak.</p><p>Lakukan logika penghapusan dengan traversal dan tracking node, lalu cetak isi SLL setelahnya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'hapus', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL: 5 -> 10 -> 15', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set node prev = null, node temp = head, ID hapus = 10', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA temp belum habis dan nilai temp != 10:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  prev = temp, temp = temp.next (maju mencari node 10)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'JIKA node ditemukan, lompati node tersebut (prev.next = temp.next)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT sisa berkas di SLL', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 14, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $linkedListLevelId,
                'judul'           => 'Memeriksa Struktur Palindrom Sederhana',
                'soal'            => '<p>Sebuah kata disimpan dalam DLL huruf demi huruf: "A" <-> "B" <-> "A". Program harus mengecek apakah susunan kata ini merupakan palindrom dengan cara membandingkan node paling depan dan node paling belakang yang bergerak ke arah tengah bersilangan.</p><p>Tentukan apakah struktur tersebut merupakan palindrom dan cetak hasil boolean-nya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'tail', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'isPal', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat DNode n1(A) <-> n2(B) <-> n3(A)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set head = n1, tail = n3, boolean isPalindrom = true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA head dan tail belum saling silang:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  JIKA head.data != tail.data MAKA isPalindrom = false', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  head = head.next (maju dari kiri)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  tail = tail.prev (mundur dari kanan)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT hasil isPalindrom', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 15, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
        ];

        //Queue Lama
        $queueLamaSoalList = [
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Operasi Enqueue dan Print pada Antrian',
                'soal'            => '<p>Sebuah sistem antrian menerima dua data berturut-turut yaitu 15 dan 30 menggunakan operasi <code>enqueue</code>. Setelah kedua data dimasukkan, sistem memanggil fungsi <code>print</code> untuk menampilkan seluruh isi antrian dari depan ke belakang.</p><p>Tentukan output dari sistem tersebut.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE(15)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE(30)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT menampilkan 15 lalu 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 1, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Operasi Dequeue dan Print pada Antrian',
                'soal'            => '<p>Terdapat antrian dengan data awal 10, 20, dan 30. Sistem kemudian menjalankan operasi <code>dequeue</code> satu kali untuk mengeluarkan elemen terdepan. Setelah itu, fungsi <code>print</code> dipanggil.</p><p>Tentukan sisa elemen yang dicetak oleh sistem.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Antrian berisi 10, 20, 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE dijalankan, angka 10 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT menampilkan sisa elemen: 20 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 2, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Antrian Barang Gudang (Enqueue & Print)',
                'soal'            => '<p>Sebuah gudang mencatat barang masuk ke dalam antrian. Tiga barang dengan ID 100, 200, dan 300 dimasukkan berturut-turut menggunakan operasi <code>enqueue</code>. Setelah itu, petugas memanggil fungsi <code>print</code> untuk melihat isi antrian.</p><p>Tentukan output yang akan tercetak.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 100, 200, 300', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT menampilkan 100 200 300', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 3, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Pengurangan Antrian Loket (Dequeue & Print)',
                'soal'            => '<p>Antrian loket awalnya berisi antrian 1, 2, 3, dan 4. Petugas memanggil dua orang pertama sehingga operasi <code>dequeue</code> dijalankan sebanyak dua kali. Kemudian petugas mengecek sisa antrian dengan operasi <code>print</code>.</p><p>Tentukan sisa antrian yang dicetak.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Antrian berisi 1, 2, 3, 4', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE 2 kali (1 dan 2 keluar)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT menampilkan sisa elemen: 3 4', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 4, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Pencatatan Cepat Antrian (Enqueue & Print)',
                'soal'            => '<p>Sistem menerima input antrian nilai 88 menggunakan <code>enqueue</code>, lalu langsung mencetaknya menggunakan <code>print</code>. Kemudian, nilai 99 masuk dengan <code>enqueue</code>, dan sistem kembali memanggil <code>print</code>.</p><p>Tentukan output baris pertama dan kedua dari sistem.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'data', 'tipe_data' => 'Queue', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 88 lalu PRINT', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 99 lalu PRINT', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 5, 'status' => 1, 'difficulty' => 'easy',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Cek Kapasitas dan Peek Antrian Layanan',
                'soal'            => '<p>Sebuah program antrian menggunakan Scanner untuk menerima kapasitas maksimal. Pengguna memasukkan kapasitas 2. Kemudian, sistem mengecek apakah antrian penuh (<code>isFull</code>). Selanjutnya, data 101 dimasukkan (<code>enqueue</code>) dan sistem mengecek elemen terdepan menggunakan <code>peek</code>.</p><p>Tentukan output pengecekan kapasitas dan nilai elemen terdepan.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: max = 2', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Cek isFull() -> FALSE', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE(101)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PEEK() -> 101', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 6, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Mengosongkan Sisa Antrian',
                'soal'            => '<p>Tanpa menggunakan input Scanner, sebuah antrian diisi dengan data 55 dan 66. Program lalu menjalankan <code>dequeue</code> satu kali, disusul dengan pemanggilan <code>clear</code>. Terakhir, program memanggil <code>isEmpty</code>.</p><p>Tentukan status <code>isEmpty</code> di akhir program.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'status', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE(55), ENQUEUE(66)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE() -> 55 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'CLEAR() -> sisa elemen dihapus', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Cek isEmpty() -> TRUE', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 7, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Simulasi Operasi Layanan Queue',
                'soal'            => '<p>Dengan menggunakan Scanner, program menerima input 3 buah data secara berurutan: 5, 15, 25 untuk di-<code>enqueue</code>. Program mencetak isi antrian dengan <code>print</code>, lalu melakukan <code>dequeue</code> satu kali, dan memanggil <code>print</code> lagi.</p><p>Bagaimana bentuk output print pertama dan kedua?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'dt', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input 5, 15, 25 lalu ENQUEUE', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT -> 5 15 25', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE() -> 5 keluar', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT -> 15 25', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 8, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Batas Kapasitas Antrian',
                'soal'            => '<p>Menggunakan Scanner, admin mengatur kapasitas antrian maksimal (<code>max</code>) sebesar 3. Admin kemudian memasukkan angka 10, 20, dan 30 secara berurutan menggunakan <code>enqueue</code>. Setelah itu, sistem mengecek apakah antrian sudah penuh dengan memanggil fungsi <code>isFull</code>, dilanjutkan dengan <code>peek</code> untuk melihat antrian terdepan.</p><p>Tentukan status boolean <code>isFull</code> dan hasil dari <code>peek</code>.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner max = 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 10, 20, 30', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Cek isFull() -> TRUE', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PEEK() -> 10', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 9, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Reset Ulang Antrian Pelanggan',
                'soal'            => '<p>Sebuah toko (tanpa Scanner) memasukkan nomor antrian 5, 6, dan 7 menggunakan <code>enqueue</code>. Kasir mencetak antrian dengan <code>print</code>. Karena sistem error, kasir memanggil fungsi <code>clear</code> untuk mengosongkan seluruh antrian, dan kemudian mengeceknya menggunakan <code>isEmpty</code>.</p><p>Tentukan output cetakan pertama dan status <code>isEmpty</code> setelah di-clear.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'status', 'tipe_data' => 'boolean', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 5, 6, 7', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT -> 5 6 7', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'CLEAR() -> antrian dikosongkan', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Cek isEmpty() -> TRUE', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 10, 'status' => 1, 'difficulty' => 'medium',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Batas Kapasitas Antrean Wahana Bermain',
                'soal'            => '<p>Sebuah taman bermain menggunakan Scanner untuk mengatur kapasitas (<code>max</code>) antrean wahana. Petugas memasukkan batas kapasitas 3. Ada 5 anak dengan ID: 11, 22, 33, 44, dan 55 yang masuk antrean satu per satu. Jika antrean penuh (<code>isFull()</code>), sistem langsung mencetak "Penuh" dan proses dihentikan (break).</p><p>Berapa banyak anak yang berhasil masuk ke antrean?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'max', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner max = 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop elemen: 11, 22, 33, 44, 55', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(11), enqueue(22), enqueue(33)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Saat elemen 44 masuk, isFull() true -> cetak Penuh, lalu break', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print total ukuran antrean -> 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 11, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Simulasi Reset Antrean Otomatis di Klinik',
                'soal'            => '<p>Di sebuah klinik (tanpa Scanner), 3 pasien mendaftar dengan ID: 101, 102, 103 (<code>enqueue</code>). Dokter kemudian memanggil ketiga pasien secara berurutan (<code>dequeue</code>). Setiap kali <code>dequeue</code> dijalankan, sistem mengecek: jika nilai <code>front &gt; rear</code>, maka sistem langsung me-reset <code>front</code> dan <code>rear</code> menjadi -1.</p><p>Berapakah nilai <code>front</code> dan <code>rear</code> di akhir program?</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'front', 'tipe_data' => 'int', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'enqueue(101), enqueue(102), enqueue(103)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 101, dequeue() -> 102', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'dequeue() -> 103, front naik melewati rear', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Kondisi front > rear true -> reset front = -1, rear = -1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print Front dan Rear', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 12, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Pengarsipan Digital Antrean ke Stack',
                'soal'            => '<p>Sistem perpustakaan menerima 3 ID buku menggunakan Scanner: 1, 2, dan 3 yang dimasukkan ke antrean (Queue). Di sore hari, sistem memindahkan seluruh buku tersebut dari Queue ke dalam arsip (Stack). Selama antrean tidak kosong, sistem akan melakukan <code>dequeue</code> dan datanya langsung di-<code>push</code> ke Stack.</p><p>Tentukan ID buku yang berada di posisi paling atas (top) pada arsip Stack.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'q', 'tipe_data' => 'Queue', 'konversi' => 0],
                    ['variabel' => 'st', 'tipe_data' => 'Stack', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: ENQUEUE 1, 2, 3 ke Queue', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop memindahkan elemen: DEQUEUE 1 -> PUSH 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE 2 -> PUSH 2', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'DEQUEUE 3 -> PUSH 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT elemen top dari Stack', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 13, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Pembalikan Urutan Mobil Keluar Gang',
                'soal'            => '<p>Tiga mobil terjebak di gang buntu dengan antrean [1, 2, 3]. Untuk keluar, mereka harus diputar balik menjadi [3, 2, 1] tanpa Scanner. Tekniknya: pindahkan seluruh mobil dari Queue ke dalam tumpukan sementara (Stack) menggunakan <code>dequeue</code> dan <code>push</code>. Setelah antrean dikosongkan, mobil dikembalikan dari Stack ke Queue menggunakan <code>pop</code> dan <code>enqueue</code>.</p><p>Tentukan hasil cetakan antrean setelah dibalik.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'q', 'tipe_data' => 'Queue', 'konversi' => 0],
                    ['variabel' => 'st', 'tipe_data' => 'Stack', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'ENQUEUE 1, 2, 3', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Pindahkan ke Stack: push(dequeue()) berulang hingga Queue kosong', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Reset index Queue', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Pindahkan kembali: enqueue(pop()) hingga Stack kosong', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'PRINT Queue -> 3 2 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 14, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
            [
                'id'              => Str::uuid(),
                'id_level'        => $queueLamaLevelId,
                'judul'           => 'Validasi Antrean Palindrom',
                'soal'            => '<p>Sistem mengecek apakah 3 tiket yang dimasukkan pengunjung dengan Scanner merupakan urutan palindrom (misal: 1 2 1). Setiap input langsung dimasukkan ke Queue (<code>enqueue</code>) dan ke Stack (<code>push</code>) sekaligus. Kemudian, elemen diuji dengan membandingkan hasil <code>dequeue()</code> dengan <code>pop()</code>.</p><p>Jika input yang diberikan adalah 1, 2, dan 1, tentukan apakah susunan tiket tersebut membentuk palindrom.</p>',
                'kunci_tipe_data' => json_encode([
                    ['variabel' => 'isPalin', 'tipe_data' => 'boolean', 'konversi' => 0],
                ]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Input Scanner: 1, 2, 1', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Simpan ke Queue dan Stack secara bersamaan', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Loop pengecekan: Bandingkan dequeue() dengan pop()', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '1 == 1, 2 == 2, 1 == 1. Semua sama, isPalin = true', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'print nilai isPalin', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'order'      => 15, 'status' => 1, 'difficulty' => 'hard',
                'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null,
            ],
        ];

        // Insert Soal Queue
        $allSoalList = array_merge($soalList, $linkedListSoalList, $queueLamaSoalList);

        foreach (array_chunk($allSoalList, 500) as $chunk) {
            DB::table('soal')->insert($chunk);
        }

        DB::table('soal')
            ->where('judul', 'Menghapus Pasien Pertama dari Antrian')
            ->update([
                'judul'           => 'Menghapus Lagu Terakhir dari Playlist',
                'soal'            => '<p>Sebuah playlist lagu disimpan dalam Single Linked List dengan urutan LaguA -> LaguB -> LaguC. Karena LaguC sudah tidak populer, admin ingin menghapus lagu terakhir dari playlist tersebut.</p><p>Telusuri node hingga sebelum node terakhir, putus sambungannya, lalu cetak isi playlist yang tersisa.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'Node', 'konversi' => 0], ['variabel' => 'temp', 'tipe_data' => 'Node', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat SLL: LaguA -> LaguB -> LaguC', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set node temp = head', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA temp.next.next tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  temp = temp.next', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Putus node terakhir (temp.next = null)', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Telusuri dan PRINT playlist tersisa', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'difficulty'     => 'medium',
                'updated_at'      => now(),
            ]);

        DB::table('soal')
            ->where('judul', 'Memeriksa Struktur Palindrom Sederhana')
            ->update([
                'judul'           => 'Menampilkan Riwayat Lagu Secara Mundur',
                'soal'            => '<p>Sebuah aplikasi musik menggunakan Double Linked List untuk menyimpan riwayat lagu: Rock <-> Jazz <-> Pop. Pengguna ingin melihat riwayat lagu dari yang terakhir diputar menuju yang pertama.</p><p>Gunakan pointer prev untuk menelusuri Double Linked List dari belakang ke depan, lalu cetak urutannya.</p>',
                'kunci_tipe_data' => json_encode([['variabel' => 'head', 'tipe_data' => 'DNode', 'konversi' => 0], ['variabel' => 'tail', 'tipe_data' => 'DNode', 'konversi' => 0]]),
                'kunci_algoritma' => json_encode([
                    ['langkah' => 'START', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Buat DLL: Rock <-> Jazz <-> Pop', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'Set head pada Rock dan tail pada Pop', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'LAKUKAN SELAMA tail tidak kosong:', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  PRINT data pada tail', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => '  tail = tail.prev', 'clue' => 0, 'konversi' => 0],
                    ['langkah' => 'END', 'clue' => 0, 'konversi' => 0],
                ]),
                'difficulty'     => 'hard',
                'updated_at'      => now(),
            ]);

        $totalQueue = count($soalList);
        $totalLinkedList = count($linkedListSoalList);
        $totalQueueLama = count($queueLamaSoalList);

        $this->command->info("SoalSeeder        : {$totalQueue} soal Queue dan {$totalLinkedList} soal Linked List dan {$totalQueueLama} soal Queue Lama berhasil di-seed.");
    }
}
