version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: new_pseudolearn
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - "3306:3306"
    networks:
      - laravel

networks:
  laravel: